title: Hasidic New Times

description: >- # this means to ignore newlines until "baseurl:"
  This is the personal website of leatheresque where you can find gems created by him.

baseurl          : ""
url              : "https://hasidic.dev"

author           : Joseph Estes

social:
  email            : yosi@hasidic.dev
  discord_id       : leatheresque#3820
  invite_link      : p5dWcctura

plugins:
  - jekyll-feed

excerpt_separator: <!--more-->

collections:
  categories:
    output: true
    permalink: /:categories/:title/
  authors:
    output: true