title: Hasidic New Times

description: >- # this means to ignore newlines until "baseurl:"
  Hasidic New Times is a new online newspaper for the Hasidic world, guest contributions and opinion pieces welcome

baseurl          : ""
url              : "https://hasidic.dev"

author           : Joseph Estes

social:
  email            : yosi@hasidic.dev
  invite_link      : 7XezzYwe9U

plugins:
  - jekyll-feed

excerpt_separator: <!--more-->

collections:
  categories:
    output: true
    permalink: /:categories/:title/
  authors:
    output: true